site_name: Spring Content
theme: bootstrap4
nav:
  - Home: index.md
  - Guides:
    - Java API: spring-content-fs-docs.md
    - REST API: spring-content-rest-docs.md
    - Versions: spring-content-with-versions-docs.md
plugins:
  - search
  - git-committers:
      repository: paulcwarren/spring-content
      branch: master
