site_name: Content Services for Spring
theme: bootstrap4
nav:
  - Home: index.md
  - Guides:
    - Java API: spring-content-fs-docs.md
    - REST API: spring-content-rest-docs.md
    - Renditions: spring-content-with-renditions-docs.md
    - Fulltext: spring-content-with-fulltext-docs.md
    - Versions: spring-content-with-versions-docs.md
    - RBAC: spring-content-with-rbac-docs.md
    - CMIS: spring-content-with-cmis-docs.md
    - Encryption: spring-content-with-encryption-docs.md
plugins:
  - search
  - git-committers:
      repository: paulcwarren/spring-content
      branch: main
